Completedata <- read.table("household_power_consumption.txt",header = TRUE, sep = ";")
Completedata$Date <- as.Date(Completedata$Date, "%d/%m/%Y")
Finaldata <- subset(Completedata, (Date == "2007-02-01" | Date == "2007-02-02"))
Finaldata$Global_active_power <- as.numeric(as.character(Finaldata$Global_active_power))
hist(Finaldata$Global_active_power, xlab = "Global Active Power (Kilowatts)", col = "red", main = "Global Active Power")
dev.copy(png,"plot1.png",width = 480, height = 480, units = "px")
dev.off()