Completedata <- read.table("household_power_consumption.txt",header = TRUE, sep = ";")
Completedata$Date <- as.Date(Completedata$Date, "%d/%m/%Y")
Finaldata <- subset(Completedata, (Date == "2007-02-01" | Date == "2007-02-02"))
Finaldata$Global_active_power <- as.numeric(as.character(Finaldata$Global_active_power))
Finaldata$datetime <- strptime(paste(Finaldata$Date, Finaldata$Time, sep=" "), "%Y-%m-%d %H:%M:%S") 
Finaldata$Sub_metering_1 <- as.numeric(as.character(Finaldata$Sub_metering_1))
Finaldata$Sub_metering_2 <- as.numeric(as.character(Finaldata$Sub_metering_2))
Finaldata$Sub_metering_3 <- as.numeric(as.character(Finaldata$Sub_metering_3))
Finaldata$Global_reactive_power <- as.numeric(as.character(Finaldata$Global_reactive_power))
Finaldata$Global_reactive_power <- as.numeric(as.character(Finaldata$Global_reactive_power))
Finaldata$Voltage <- as.numeric(as.character(Finaldata$Voltage))
png("plot4.png",width = 480, height = 480, units = "px")
par(mfrow = c(2,2))
par(mar = c(4,4,2,1))
par(oma = c(0,0,2,0))
plot(datetime, Finaldata$Global_active_power, type="l", xlab="", ylab="Global Active Power")
plot(datetime, Finaldata$Voltage, type="l", ylab = "Voltage")
plot(datetime, Finaldata$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(datetime, Finaldata$Sub_metering_2, col = "red")
lines(datetime, Finaldata$Sub_metering_3, col = "blue")
legend("topright", col = c("black","red","blue"), lty = 1, lwd = 2, bty="n", legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(datetime, Finaldata$Global_reactive_power, type="l", ylab="Global_reactive_power")
dev.off()
