Completedata <- read.table("household_power_consumption.txt",header = TRUE, sep = ";")
Completedata$Date <- as.Date(Completedata$Date, "%d/%m/%Y")
Finaldata <- subset(Completedata, (Date == "2007-02-01" | Date == "2007-02-02"))
Finaldata$Global_active_power <- as.numeric(as.character(Finaldata$Global_active_power))
datetime <- strptime(paste(Finaldata$Date, Finaldata$Time, sep=" "), "%Y-%m-%d %H:%M:%S") 
plot(datetime, Finaldata$Global_active_power, type="l", xlab="", ylab="Global Active Power (kilowatts)")
dev.copy(png,"plot2.png",width = 480, height = 480, units = "px")
dev.off()