Completedata <- read.table("household_power_consumption.txt",header = TRUE, sep = ";")
Completedata$Date <- as.Date(Completedata$Date, "%d/%m/%Y")
Finaldata <- subset(Completedata, (Date == "2007-02-01" | Date == "2007-02-02"))
Finaldata$Global_active_power <- as.numeric(as.character(Finaldata$Global_active_power))
Finaldata$datetime <- strptime(paste(Finaldata$Date, Finaldata$Time, sep=" "), "%Y-%m-%d %H:%M:%S") 
Finaldata$Sub_metering_1 <- as.numeric(as.character(Finaldata$Sub_metering_1))
Finaldata$Sub_metering_2 <- as.numeric(as.character(Finaldata$Sub_metering_2))
Finaldata$Sub_metering_3 <- as.numeric(as.character(Finaldata$Sub_metering_3))
png("plot3.png",width = 480, height = 480, units = "px")
plot(datetime, Finaldata$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(datetime, Finaldata$Sub_metering_2, col = "red")
lines(datetime, Finaldata$Sub_metering_3, col = "blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, col=c("black", "red", "blue"))
dev.off()